数据库与客户端部分/AidProject/urls.py
# url声明
"""DjangoTest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import url, include
from AID import views
import video

# django2.0一般不用正则


urlpatterns = [

    url(r'^aid/', include('AID.urls')),
    url('^admin/', admin.site.urls),  # 管理员
    #    url('captcha/', include('captcha.urls')),  # 验证码
    url('^login/$', views.login),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('video/', include('video.urls')),
    url('myadmin/', include('myadmin.urls')),
    url('users/', include('users.urls')),
]

数据库与客户端部分/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('subscribe/<int:pk>/', views.SubscribeView.as_view(), name='subscribe'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('<int:pk>/collect_videos/', views.CollectListView.as_view(), name='collect_videos'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
]

数据库与客户端部分/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class User(AbstractUser):

    nickname = models.CharField(blank=True, null=True, max_length=20)
    avatar = models.FileField(upload_to='avatar/')
    mobile = models.CharField(blank=True, null=True, max_length=13)
    subscribe = models.BooleanField(default=False)

    type = models.IntegerField(default=0)  # 0为志愿者，1为培训，2为招募者
    gender = models.BooleanField(null=True)  # 男为1，女为0
    signature = models.CharField(null=True, max_length=200)  # 自我介绍
    work = models.CharField(max_length=30, null=True)  # 职业
    age = models.IntegerField(null=True)  # 年龄
    enable = models.BooleanField(default=True)  # 账户是否可用
    isAttest = models.BooleanField(default=False)  # 账户是否被认证
    num = models.IntegerField(null=True)  # 备用字段
    class Meta:
        db_table = "v_user"


class Feedback(models.Model):
    contact = models.CharField(blank=True, null=True, max_length=20)
    content = models.CharField(blank=True, null=True, max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        db_table = "v_feedback"

数据库与客户端部分/templates/myadmin/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/semantic.custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin.css' %}"/>
    <title>后台管理</title>
</head>
<body>
<div class="ui inverted huge borderless fixed fluid menu">
    <a class="header item" href="{% url 'myadmin:index' %}">
        <img src="{% static 'img/logo.png' %}" id="logo">后台管理
    </a>
    <div class="right menu">
        <a class="item" href="../../video/" target="_blank">前台首页</a>
        <a class="item" href="{% url 'myadmin:index' %}">后台首页</a>
        <a class="item">{{ user }}</a>
        <a class="item" href="{% url 'myadmin:logout' %}">退出</a>
    </div>
</div>
<div class="ui grid">
    <div class="row">
        <div class="column" id="sidebar">
            <div class="ui secondary vertical fluid menu">
                <a class="item" href="{% url 'myadmin:index' %}" id="index">总览</a>
                <div class="ui divider"></div>
                <a class="item" href="{% url 'myadmin:video_list' %}" id="video_list">视频列表</a>
                <a class="item" href="{% url 'myadmin:video_add' %}" id="video_add">添加视频</a>
                <div class="ui divider"></div>
                <a class="item" href="{% url 'myadmin:classification_list' %}" id="classification_list">分类列表</a>
                <a class="item" href="{% url 'myadmin:classification_add' %}" id="classification_add">添加分类</a>
                <div class="ui divider"></div>
                <a class="item" href="{% url 'myadmin:user_list' %}" id="user_list">用户列表</a>
                <a class="item" href="{% url 'myadmin:user_add' %}" id="user_add">添加用户</a>
                <div class="ui divider"></div>
                <a class="item" href="{% url 'myadmin:comment_list' %}" id="comment_list">评论列表</a>
                <div class="ui divider"></div>
                <a class="item" href="{% url 'myadmin:subscribe'  %}" id="subscribe">订阅通知</a>
                <a class="item" href="{% url 'myadmin:feedback_list'  %}" id="feedback_list">用户反馈</a>
            </div>
        </div>
    </div>
    <div class="column" id="content">
        {% block content %}
        {% endblock content %}
    </div>
</div>
</div>

{% block modal %}
{% endblock modal %}
<script src="https://cdn.staticfile.org/jquery/1.9.0/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.js"></script>
<script src="{% static 'js/myadmin/admin_nav.js' %}"></script>
{% block javascript %}
{% endblock javascript %}


</body>
</html>

数据库与客户端部分/templates/myadmin/classification_add.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>分类添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:classification_add' %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>分类名称</label>
                    {{ form.title }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.status}}
                      <label>是否启用</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">添加</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

数据库与客户端部分/templates/myadmin/classification_add_success.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>分类添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <h3>添加成功！</h3>
            <h3><a href="{% url 'myadmin:classification_list' %}">&lt;&lt;返回列表</a></h3>
        </div>
    </div>
</div>


{% endblock content %}