数据库与客户端部分/AidProject/urls.py
# url声明
"""DjangoTest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import url, include
from AID import views
import video

# django2.0一般不用正则


urlpatterns = [

    url(r'^aid/', include('AID.urls')),
    url('^admin/', admin.site.urls),  # 管理员
    #    url('captcha/', include('captcha.urls')),  # 验证码
    url('^login/$', views.login),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('video/', include('video.urls')),
    url('myadmin/', include('myadmin.urls')),
    url('users/', include('users.urls')),
]

数据库与客户端部分/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('subscribe/<int:pk>/', views.SubscribeView.as_view(), name='subscribe'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('<int:pk>/collect_videos/', views.CollectListView.as_view(), name='collect_videos'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
]

数据库与客户端部分/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class User(AbstractUser):

    nickname = models.CharField(blank=True, null=True, max_length=20)
    avatar = models.FileField(upload_to='avatar/')
    mobile = models.CharField(blank=True, null=True, max_length=13)
    subscribe = models.BooleanField(default=False)

    type = models.IntegerField(default=0)  # 0为志愿者，1为培训，2为招募者
    gender = models.BooleanField(null=True)  # 男为1，女为0
    signature = models.CharField(null=True, max_length=200)  # 自我介绍
    work = models.CharField(max_length=30, null=True)  # 职业
    age = models.IntegerField(null=True)  # 年龄
    enable = models.BooleanField(default=True)  # 账户是否可用
    isAttest = models.BooleanField(default=False)  # 账户是否被认证
    num = models.IntegerField(null=True)  # 备用字段
    class Meta:
        db_table = "v_user"


class Feedback(models.Model):
    contact = models.CharField(blank=True, null=True, max_length=20)
    content = models.CharField(blank=True, null=True, max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        db_table = "v_feedback"

数据库与客户端部分/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.core.exceptions import ValidationError
from .models import Feedback
from users.models import User


def avatar_file_size(value):
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('头像文件太大了，请限制在2M之内')


class ProfileForm(forms.ModelForm):
    nickname = forms.CharField(min_length=1,max_length=20,required=False,
                               error_messages={
                                   'min_length': '昵称至少4个字符',
                                   'min_length': '昵称不能多于20个字符',
                               },
                               widget=forms.TextInput())
    avatar = forms.ImageField(required=False, validators=[avatar_file_size],
                              widget=forms.FileInput(attrs={'class' : 'n'}))
    email = forms.EmailField(required=False,
                             error_messages={
                                 'invalid': '请输入有效的Email地址',
                             },
                             widget=forms.EmailInput())
    gender = forms.CharField(min_length=1,max_length=1,required=False,
                             widget=forms.HiddenInput())

    mobile = forms.CharField(min_length=11,max_length=11,required=False,
                             error_messages={
                                 'min_length': '请输入11位手机号',
                                 'max_length': '请输入11位手机号',
                             },
                             widget=forms.NumberInput())

    class Meta:
        model = User
        fields = ['nickname', 'avatar', 'email', 'gender', 'mobile']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(min_length=4,max_length=30,
                               error_messages={
                                   'min_length': '用户名不少于4个字符',
                                   'max_length': '用户名不能多于30个字符',
                                   'required': '用户名不能为空',
                               },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名'}))
    password = forms.CharField(min_length=8,max_length=30,
                               error_messages={
                                   'min_length': '密码不少于8个字符',
                                   'max_length': '密码不能多于30个字符',
                                   'required': '密码不能为空',
                               },
                               widget=forms.PasswordInput(attrs={'placeholder': '请输入密码'}))

    class Meta:
        model = User
        fields = ['username', 'password']

    error_messages = {'invalid_login': '用户名或密码错误', }


class SignUpForm(UserCreationForm):
    username = forms.CharField(min_length=4,max_length=30,
                               error_messages={
                                   'min_length': '用户名不少于4个字符',
                                   'max_length': '用户名不能多于30个字符',
                                   'required': '用户名不能为空',
                               },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名'}))
    password1 = forms.CharField(min_length=8, max_length=30,
                                error_messages={
                                    'min_length': '密码不少于8个字符',
                                    'max_length': '密码不能多于30个字符',
                                    'required': '密码不能为空',
                                },
                                widget=forms.PasswordInput(attrs={'placeholder': '请输入密码'}))
    password2 = forms.CharField(min_length=8,max_length=30,
                                error_messages={
                                    'min_length': '密码不少于8个字符',
                                    'max_length': '密码不能多于30个字符',
                                    'required': '密码不能为空',
                                },
                                widget=forms.PasswordInput(attrs={'placeholder': '请确认密码'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

    error_messages = {'password_mismatch': '两次密码不一致', }


class ChangePwdForm(PasswordChangeForm):
    old_password = forms.CharField(error_messages={'required': '不能为空',},
        widget=forms.PasswordInput(attrs={'placeholder': '请输入旧密码'})
    )
    new_password1 = forms.CharField(error_messages={'required': '不能为空',},
        widget=forms.PasswordInput(attrs={'placeholder': '请输入新密码'})
    )
    new_password2 = forms.CharField(error_messages={'required': '不能为空',},
        widget=forms.PasswordInput(attrs={'placeholder': '请输入确认密码'})
    )

class SubscribeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['subscribe']

class FeedbackForm(forms.ModelForm):
    content = forms.CharField(min_length=4,max_length=200,
                               error_messages={
                                   'min_length': '至少4个字符',
                                   'max_length': '不能多于200个字符',
                                   'required':'内容不能为空'
                               },
                               widget=forms.Textarea(attrs={'placeholder': '请输入内容'}))
    contact = forms.CharField(required=False,
                              widget=forms.TextInput(attrs={'placeholder':'请输入联系方式'}))
    class Meta:
        model = Feedback
        fields = ['content', 'contact']

数据库与客户端部分/users/views.py
from helpers import AuthorRequiredMixin, get_page_list
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import *
from django.views import generic
from .models import Feedback
from .forms import ProfileForm, SignUpForm, UserLoginForm, ChangePwdForm, SubscribeForm, FeedbackForm
User = get_user_model()

def login(request):
    if request.method == 'POST':
        next = request.POST.get('next', '/')
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                # return redirect('home')
                return redirect(next)
        else:
            print(form.errors)
    else:
        next = request.GET.get('next', '/')
        form = UserLoginForm()
    print(next)
    return render(request, 'registration/login.html', {'form': form, 'next':next})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password1)
            auth_login(request, user)
            return redirect('home')
        else:
            print(form.errors)
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def logout(request):
    auth_logout(request)
    return redirect('home')


def change_password(request):
    if request.method == 'POST':
        form = ChangePwdForm(request.user, request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if not user.is_staff and not user.is_superuser:
                user.save()
                update_session_auth_hash(request, user)  # 更新session 非常重要！
                messages.success(request, '修改成功')
                return redirect('users:change_password')
            else:
                messages.warning(request, '无权修改管理员密码')
                return redirect('users:change_password')
        else:
            print(form.errors)
    else:
        form = ChangePwdForm(request.user)
    return render(request, 'registration/change_password.html', {
        'form': form
    })


class ProfileView(LoginRequiredMixin,AuthorRequiredMixin, generic.UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'users/profile.html'

    def get_success_url(self):
        messages.success(self.request, "保存成功")
        return reverse('users:profile', kwargs={'pk': self.request.user.pk})


class SubscribeView(LoginRequiredMixin,AuthorRequiredMixin, generic.UpdateView):
    model = User
    form_class = SubscribeForm
    template_name = 'users/subscribe.html'

    def get_success_url(self):
        messages.success(self.request, "保存成功")
        return reverse('users:subscribe', kwargs={'pk': self.request.user.pk})

class FeedbackView(LoginRequiredMixin, generic.CreateView):

    model = Feedback
    form_class = FeedbackForm
    template_name = 'users/feedback.html'


    def post(self, request, *args, **kwargs):
        was_limited = getattr(request, 'limited', False)
        if was_limited:
            messages.warning(self.request, "操作太频繁了，请1分钟后再试")
            return render(request, 'users/feedback.html', {'form': FeedbackForm()})
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, "提交成功")
        return reverse('users:feedback')

class CollectListView(generic.ListView):
    model = User
    template_name = 'users/collect_videos.html'
    context_object_name = 'video_list'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CollectListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        return context
    def get_queryset(self):
        user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        videos = user.collected_videos.all()
        return videos


class LikeListView(generic.ListView):
    model = User
    template_name = 'users/like_videos.html'
    context_object_name = 'video_list'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(LikeListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        page_list = get_page_list(paginator, page)
        context['page_list'] = page_list
        return context

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        videos = user.liked_videos.all()
        return videos

数据库与客户端部分/templates/users/collect_videos.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<h3 class="ui header">我的收藏</h3>
<div class="ui unstackable items">

    {% for item in video_list %}
    <div class="item">
        <div class="ui tiny image">
            {% thumbnail item.cover "300x200" crop="center" as im %}
            <img class="ui image" src="{{ im.url }}">
            {% empty %}
            {% endthumbnail %}
        </div>
        <div class="middle aligned content">
            <a class="header" href="{% url 'video:detail' item.pk %}">{{ item.title }}</a>
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}

</div>

{% include "base/page_nav.html" %}

{% endblock content %}

数据库与客户端部分/templates/users/feedback.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}


<div class="v-settings">
    <div class="ui two column grid ">
        <div class="four wide column">
            {% include "base/left_nav.html" %}
        </div>
        <div class="twelve wide column">
            <div class="v-settings-content">
                <form class="ui form" novalidate action="{% url 'users:feedback' %}" enctype="multipart/form-data" method="post" role="form">
                    {% csrf_token %}
                    <div class="sixteen wide  field ">
                        <label>反馈与建议</label>
                        <div class="field">
                            {{ form.content }}
                        </div>
                    </div>

                    <div class="sixteen wide  field ">
                        <label>联系方式</label>
                        <div class="field">
                            {{ form.contact }}
                        </div>
                    </div>

                    <button class="ui primary button" type="submit">提交</button>

                    {% include "base/form_errors.html" %}
                    {% include "base/form_messages.html" %}

                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript">
$('.ui .dropdown').dropdown();

</script>
<script src="{% static 'js/left_nav.js' %}"></script>
{% endblock javascript %}

数据库与客户端部分/templates/users/like_videos.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<h3 class="ui header">我的喜欢</h3>
<div class="ui unstackable items">

    {% for item in video_list %}
    <div class="item">
        <div class="ui tiny image">
            {% thumbnail item.cover "300x200" crop="center" as im %}
            <img class="ui image" src="{{ im.url }}">
            {% empty %}
            {% endthumbnail %}
        </div>
        <div class="middle aligned content">
            <a class="header" href="{% url 'video:detail' item.pk %}">{{ item.title }}</a>
        </div>
    </div>
    {% empty %}
    <h3>暂无数据</h3>
    {% endfor %}

</div>


{% include "base/page_nav.html" %}

{% endblock content %}

数据库与客户端部分/templates/users/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}


<div class="v-settings">
    <div class="ui two column grid ">
        <div class="four wide column">
            {% include "base/left_nav.html" %}
        </div>
        <div class="twelve wide column">
            <div class="v-settings-content">

                <form class="ui form" novalidate method="post" action="{% url 'users:profile' form.instance.pk %}"
                      enctype="multipart/form-data" role="form">
                    {% csrf_token %}
                    <div class="sixteen wide inline field v-form-field">
                        <label>头像</label>
                        <div class="v-inline-middle">
                            <label for="id_avatar">
                                {% thumbnail user.avatar "200x200" crop="center" as im %}
                                  <img class="ui mini circular image" src="{{ im.url }}">
                                {% empty %}
                                <img class="ui mini circular  image" src="{% static 'img/img_default_avatar.png' %}">
                                {% endthumbnail %}
                            </label>
                            {{form.avatar}}
                            <span id="file_is_choose" class="n">文件已选择</span>

                        </div>
                    </div>

                    <div class="sixteen wide inline field v-form-field">
                        <label>昵称</label>
                        {{form.nickname}}
                    </div>

                    <div class="sixteen wide inline field v-form-field">
                        <label>Email</label>
                        {{form.email}}
                    </div>

                    <div class="sixteen wide inline field v-form-field">
                        <label>手机号</label>
                        {{form.mobile}}
                    </div>

                    <div class="sixteen wide inline field v-form-field">
                        <label>性别</label>
                        <div class="ui selection  dropdown">
                            {{form.gender}}
                            <i class="dropdown icon"></i>
                            <div class="default text">请选择</div>
                            <div class="menu">
                                <div class="item" data-value="1">男</div>
                                <div class="item" data-value="0">女</div>
                            </div>
                        </div>
                    </div>

                    <button class="ui primary button" type="submit">保存</button>

                    {% include "base/form_errors.html" %}
                    {% include "base/form_messages.html" %}

                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript">

$(function(){

    $('.ui .dropdown').dropdown();

    $("#id_avatar").change(function(){
        $("#file_is_choose").show()
    });

});

</script>
<script src="{% static 'js/left_nav.js' %}"></script>
{% endblock javascript %}

数据库与客户端部分/templates/users/subscribe.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}


<div class="v-settings">
  <div class="ui two column grid ">
     <div class="four wide column">
         {% include "base/left_nav.html" %}
     </div>
     <div class="twelve wide column">
      <div class="v-settings-content">
        <form class="ui form" method="post" action="{% url 'users:subscribe' form.instance.pk %}" enctype="multipart/form-data" role="form">
            {% csrf_token %}
           <div class="sixteen wide inline field v-form-field">
              <div class="ui checkbox">
                  {{form.subscribe}}
                  <label>接收邮件通知</label>
                </div>
            </div>
            <button class="ui primary button" type="submit">保存</button>
            {% include "base/form_errors.html" %}
            {% include "base/form_messages.html" %}
        </form>
      </div>
     </div>

  </div>
</div>

{% endblock content %}

{% block javascript %}
<script  type="text/javascript" >
$('.ui .dropdown').dropdown();
</script>
<script src="{% static 'js/left_nav.js' %}"></script>
{% endblock javascript %}